version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - nfsmount:/var/www/codebase
    ports:
      - 80:80
    networks:
      - app

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'sf_db'
      MYSQL_USER: 'sf_app'
      MYSQL_PASSWORD: 't4!TpSc4n'
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
    networks:
      - app

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - nfsmount:/var/www/codebase
    networks:
      - app

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      - app

  redis:
    image: redis:alpine3.13
    ports:
      - 6379:6379
    networks:
      - app

networks:
  app:

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"

#  data-volume:
#    external: true
